Repository KakaoTech-14-All-in-one-move/AIM-14-BE, pull requests merged in 2024-11, with the labels that each got.

#7 Aim 53 impl Websocket Server
  src/main/java/com/example/pitching/call/config/SecurityConfig.java
  src/main/java/com/example/pitching/call/controller/VoiceController.java
  src/main/java/com/example/pitching/call/dto/ChannelType.java
  src/main/java/com/example/pitching/call/dto/Subscription.java
  src/main/java/com/example/pitching/call/dto/VoiceState.java
  src/main/java/com/example/pitching/call/exception/CommonException.java
  src/main/java/com/example/pitching/call/exception/DuplicateOperationException.java
  src/main/java/com/example/pitching/call/exception/ErrorCode.java
  src/main/java/com/example/pitching/call/exception/InvalidValueException.java
  src/main/java/com/example/pitching/call/exception/WrongAccessException.java
  src/main/java/com/example/pitching/call/handler/CallWebSocketHandler.java
  src/main/java/com/example/pitching/call/handler/ConvertService.java
  src/main/java/com/example/pitching/call/handler/ReplyHandler.java
  src/main/java/com/example/pitching/call/handler/ServerStreamManager.java
  src/main/java/com/example/pitching/call/operation/Data.java
  src/main/java/com/example/pitching/call/operation/Event.java
  src/main/java/com/example/pitching/call/operation/code/Operation.java
  src/main/java/com/example/pitching/call/operation/code/RequestOp.java
  src/main/java/com/example/pitching/call/operation/code/RequestOperation.java
  src/main/java/com/example/pitching/call/operation/code/ResponseOperation.java
  src/main/java/com/example/pitching/call/operation/request/ChannelRequest.java
  src/main/java/com/example/pitching/call/operation/request/Heartbeat.java
  src/main/java/com/example/pitching/call/operation/request/Init.java
  src/main/java/com/example/pitching/call/operation/request/Server.java
  src/main/java/com/example/pitching/call/operation/request/ServerRequest.java
  src/main/java/com/example/pitching/call/operation/request/StateRequest.java
  src/main/java/com/example/pitching/call/operation/response/ChannelLeaveResponse.java
  src/main/java/com/example/pitching/call/operation/response/ChannelResponse.java
  src/main/java/com/example/pitching/call/operation/response/EmptyResponse.java
  src/main/java/com/example/pitching/call/operation/response/ErrorResponse.java
  src/main/java/com/example/pitching/call/operation/response/HeartbeatAck.java
  src/main/java/com/example/pitching/call/operation/response/Hello.java
  src/main/java/com/example/pitching/call/operation/response/HelloResponse.java
  src/main/java/com/example/pitching/call/operation/response/Response.java
  src/main/java/com/example/pitching/call/operation/response/ServerAck.java
  src/main/java/com/example/pitching/call/operation/response/data/HelloData.java
  src/main/java/com/example/pitching/call/operation/response/data/ServerData.java
  src/main/java/com/example/pitching/call/server/VoiceSfuServer.java
  src/main/java/com/example/pitching/call/service/ActiveUserManager.java
  src/main/java/com/example/pitching/call/service/ConvertService.java
  src/main/java/com/example/pitching/call/service/ServerStreamManager.java
  src/main/java/com/example/pitching/call/service/UdpAddressManager.java
  src/main/java/com/example/pitching/call/service/VoiceStateManager.java
  src/main/resources/application.yml
  src/test/java/com/example/pitching/voice/handler/CallWebSocketHandlerTest.java
Labels: feat

#9 Aim 50 implementing the login
  .gitignore
  HELP.md
  build.gradle
  src/main/java/com/example/pitching/auth/config/WebfluxSecurityConfig.java
  src/main/java/com/example/pitching/auth/controller/AuthController.java
  src/main/java/com/example/pitching/auth/domain/TokenStatus.java
  src/main/java/com/example/pitching/auth/domain/User.java
  src/main/java/com/example/pitching/auth/dto/ExistsEmailResponse.java
  src/main/java/com/example/pitching/auth/dto/LoginRequest.java
  src/main/java/com/example/pitching/auth/dto/LoginResponse.java
  src/main/java/com/example/pitching/auth/dto/RefreshRequest.java
  src/main/java/com/example/pitching/auth/dto/SignupRequest.java
  src/main/java/com/example/pitching/auth/dto/TokenInfo.java
  src/main/java/com/example/pitching/auth/dto/UserInfo.java
  src/main/java/com/example/pitching/auth/exception/AuthenticationException.java
  src/main/java/com/example/pitching/auth/exception/DuplicateEmailException.java
  src/main/java/com/example/pitching/auth/exception/InvalidCredentialsException.java
  src/main/java/com/example/pitching/auth/exception/InvalidTokenException.java
  src/main/java/com/example/pitching/auth/exception/TokenExpiredException.java
  src/main/java/com/example/pitching/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/pitching/auth/jwt/JwtTokenProvider.java
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2FailureHandler.java
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/pitching/auth/repository/UserRepository.java
  src/main/java/com/example/pitching/auth/service/AuthService.java
  src/main/java/com/example/pitching/auth/userdetails/CustomUserDetails.java
  src/main/java/com/example/pitching/auth/userdetails/CustomUserDetailsService.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/test/java/com/example/pitching/PitchingApplicationTests.java
  src/test/java/com/example/pitching/auth/config/BCryptPasswordEncoderTest.java
  src/test/java/com/example/pitching/auth/userdetails/CustomUserDetailsServiceTest.java
Labels: refactor, feat

#11 return 401 error code when expired token
  src/main/java/com/example/pitching/auth/exception/AuthenticationException.java
  src/main/java/com/example/pitching/auth/exception/InvalidCredentialsException.java
  src/main/java/com/example/pitching/auth/exception/InvalidTokenException.java
  src/main/java/com/example/pitching/auth/exception/TokenExpiredException.java
Labels: refactor, fix

#13 AIM-69 fix: authentication username to userdetails
  src/main/java/com/example/pitching/auth/config/WebfluxSecurityConfig.java
Labels: fix

#15 Aim 78 implement update profile image
  .gitignore
  src/main/java/com/example/pitching/auth/config/WebfluxSecurityConfig.java
  src/main/java/com/example/pitching/auth/domain/User.java
  src/main/java/com/example/pitching/auth/dto/UserInfo.java
  src/main/java/com/example/pitching/auth/userdetails/CustomUserDetails.java
  src/main/java/com/example/pitching/user/config/WebConfig.java
  src/main/java/com/example/pitching/user/controller/UserController.java
  src/main/java/com/example/pitching/user/service/FileStorageService.java
  src/main/java/com/example/pitching/user/service/UserService.java
  src/main/resources/application.yml
Labels: feat

#19 Aim 99 implement update username
  build.gradle
  src/main/java/com/example/pitching/auth/domain/User.java
  src/main/java/com/example/pitching/user/controller/UserController.java
  src/main/java/com/example/pitching/user/dto/UpdateUsernameRequest.java
  src/main/java/com/example/pitching/user/service/UserService.java
Labels: feat

#21 Aim 101 implement user withdrawal
  src/main/java/com/example/pitching/user/controller/UserController.java
  src/main/java/com/example/pitching/user/service/UserService.java
Labels: feat

#23 Aim 104 implement refactor entity
  build.gradle
  src/main/java/com/example/pitching/auth/domain/User.java
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/pitching/auth/repository/UserRepository.java
  src/main/resources/schema.sql
  src/test/java/com/example/pitching/auth/userdetails/CustomUserDetailsServiceTest.java
Labels: refactor

#25 AIM-108 add: profile image parameter
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2SuccessHandler.java
Labels: refactor

#29 Aim 143 implement server domain
  src/main/java/com/example/pitching/auth/domain/User.java
  src/main/java/com/example/pitching/auth/dto/UserInfo.java
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/pitching/auth/service/AuthService.java
  src/main/java/com/example/pitching/user/controller/ServerController.java
  src/main/java/com/example/pitching/user/domain/Server.java
  src/main/java/com/example/pitching/user/domain/UserServerMembership.java
  src/main/java/com/example/pitching/user/domain/UserServerMembershipId.java
  src/main/java/com/example/pitching/user/dto/ServerInfo.java
  src/main/java/com/example/pitching/user/dto/ServerRequest.java
  src/main/java/com/example/pitching/user/dto/ServerResponse.java
  src/main/java/com/example/pitching/user/dto/UpdateUsernameRequest.java
  src/main/java/com/example/pitching/user/repository/ServerRepository.java
  src/main/java/com/example/pitching/user/repository/UserServerMembershipRepository.java
  src/main/java/com/example/pitching/user/service/ServerService.java
  src/main/resources/schema.sql
Labels: feat

#30 Aim 144 implement channel domain
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/pitching/auth/service/AuthService.java
  src/main/java/com/example/pitching/common/error/ApiError.java
  src/main/java/com/example/pitching/common/error/GlobalExceptionHandler.java
  src/main/java/com/example/pitching/user/controller/ChannelController.java
  src/main/java/com/example/pitching/user/domain/Channel.java
  src/main/java/com/example/pitching/user/domain/Server.java
  src/main/java/com/example/pitching/user/domain/utility/ChannelCategory.java
  src/main/java/com/example/pitching/user/dto/ChannelResponse.java
  src/main/java/com/example/pitching/user/dto/CreateChannelRequest.java
  src/main/java/com/example/pitching/user/dto/ServerInfo.java
  src/main/java/com/example/pitching/user/dto/UpdateChannelNameRequest.java
  src/main/java/com/example/pitching/user/repository/ChannelRepository.java
  src/main/java/com/example/pitching/user/service/ChannelService.java
  src/main/resources/schema.sql
Labels: refactor, feat

#32 Aim 149 apply global exception handling
  src/main/java/com/example/pitching/auth/config/WebfluxSecurityConfig.java
  src/main/java/com/example/pitching/auth/controller/AuthController.java
  src/main/java/com/example/pitching/auth/dto/LoginRequest.java
  src/main/java/com/example/pitching/auth/dto/SignupRequest.java
  src/main/java/com/example/pitching/auth/exception/DuplicateEmailException.java
  src/main/java/com/example/pitching/auth/exception/InvalidCredentialsException.java
  src/main/java/com/example/pitching/auth/exception/InvalidTokenException.java
  src/main/java/com/example/pitching/auth/exception/TokenExpiredException.java
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/pitching/auth/service/AuthService.java
  src/main/java/com/example/pitching/auth/userdetails/CustomUserDetailsService.java
  src/main/java/com/example/pitching/common/error/ApiError.java
  src/main/java/com/example/pitching/common/error/GlobalExceptionHandler.java
  src/main/java/com/example/pitching/user/controller/ServerController.java
  src/main/java/com/example/pitching/user/controller/UserController.java
  src/main/java/com/example/pitching/user/domain/UserServerMembership.java
  src/main/java/com/example/pitching/user/dto/InviteMemberRequest.java
  src/main/java/com/example/pitching/user/dto/ServerRequest.java
  src/main/java/com/example/pitching/user/dto/UpdateUsernameRequest.java
  src/main/java/com/example/pitching/user/dto/UserResponse.java
  src/main/java/com/example/pitching/user/repository/ChannelRepository.java
  src/main/java/com/example/pitching/user/service/FileStorageService.java
  src/main/java/com/example/pitching/user/service/ServerService.java
  src/main/java/com/example/pitching/user/service/UserService.java
Labels: refactor
