Repository KakaoTech-14-All-in-one-move/AIM-14-BE, pull requests merged in 2024-12, with the labels that each got.

#34 Aim 158 implement unit test
  .vscode/settings.json
  src/main/java/com/example/pitching/auth/config/WebfluxSecurityConfig.java
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/pitching/user/repository/ServerRepository.java
  src/main/java/com/example/pitching/user/service/UserService.java
  src/main/resources/chema-test.sql
  src/test/java/com/example/pitching/PitchingApplicationTests.java
  src/test/java/com/example/pitching/auth/config/WebfluxSecurityConfigTest.java
  src/test/java/com/example/pitching/auth/controller/AuthControllerTest.java
  src/test/java/com/example/pitching/auth/jwt/JwtAuthenticationTest.java
  src/test/java/com/example/pitching/auth/jwt/JwtTokenProviderTest.java
  src/test/java/com/example/pitching/auth/oauth2/handler/OAuth2HandlerTest.java
  src/test/java/com/example/pitching/auth/repository/UserRepositoryTest.java
  src/test/java/com/example/pitching/auth/service/AuthServiceTest.java
  src/test/java/com/example/pitching/auth/userdetails/CustomUserDetailsServiceTest.java
  src/test/java/com/example/pitching/config/PermitAllConfig.java
  src/test/java/com/example/pitching/config/SecurityTestConfig.java
  src/test/java/com/example/pitching/user/controller/ChannelControllerTest.java
  src/test/java/com/example/pitching/user/controller/ServerControllerTest.java
  src/test/java/com/example/pitching/user/controller/UserControllerTest.java
  src/test/java/com/example/pitching/user/repository/ChannelRepositoryTest.java
  src/test/java/com/example/pitching/user/repository/ServerRepositoryTest.java
  src/test/java/com/example/pitching/user/repository/UserServerMembershipRepositoryTest.java
  src/test/java/com/example/pitching/user/service/ChannelServiceTest.java
  src/test/java/com/example/pitching/user/service/ServerServiceTest.java
  src/test/java/com/example/pitching/user/service/UserServiceTest.java
  src/test/java/com/example/pitching/voice/controller/CallControllerTest.java
Labels: feat

#36 AIM-169 add: test coverage with jacoco
  build.gradle
Labels: feat

#38 Aim 170 fix db initialization after testing
  src/test/java/com/example/pitching/auth/controller/AuthControllerTest.java
  src/test/java/com/example/pitching/auth/jwt/JwtAuthenticationTest.java
  src/test/java/com/example/pitching/auth/oauth2/handler/OAuth2HandlerTest.java
  src/test/java/com/example/pitching/auth/service/AuthServiceTest.java
  src/test/java/com/example/pitching/auth/userdetails/CustomUserDetailsServiceTest.java
  src/test/java/com/example/pitching/user/controller/ChannelControllerTest.java
  src/test/java/com/example/pitching/user/controller/ServerControllerTest.java
  src/test/java/com/example/pitching/user/controller/UserControllerTest.java
  src/test/java/com/example/pitching/user/service/ChannelServiceTest.java
  src/test/java/com/example/pitching/user/service/ServerServiceTest.java
  src/test/java/com/example/pitching/user/service/UserServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/chema-test.sql
Labels: refactor, fix

#40 Aim 172 implement swagger api
  build.gradle
  src/main/java/com/example/pitching/auth/config/WebfluxSecurityConfig.java
  src/main/java/com/example/pitching/auth/controller/AuthController.java
  src/main/java/com/example/pitching/auth/dto/ExistsEmailResponse.java
  src/main/java/com/example/pitching/auth/dto/LoginRequest.java
  src/main/java/com/example/pitching/auth/dto/LoginResponse.java
  src/main/java/com/example/pitching/auth/dto/RefreshRequest.java
  src/main/java/com/example/pitching/auth/dto/SignupRequest.java
  src/main/java/com/example/pitching/auth/dto/TokenInfo.java
  src/main/java/com/example/pitching/common/error/ApiError.java
  src/main/java/com/example/pitching/user/controller/ChannelController.java
  src/main/java/com/example/pitching/user/controller/ServerController.java
  src/main/java/com/example/pitching/user/controller/UserController.java
  src/main/java/com/example/pitching/user/dto/ChannelResponse.java
  src/main/java/com/example/pitching/user/dto/CreateChannelRequest.java
  src/main/java/com/example/pitching/user/dto/InviteMemberRequest.java
  src/main/java/com/example/pitching/user/dto/ServerRequest.java
  src/main/java/com/example/pitching/user/dto/ServerResponse.java
  src/main/java/com/example/pitching/user/dto/UpdateChannelNameRequest.java
  src/main/java/com/example/pitching/user/dto/UpdateUsernameRequest.java
  src/main/java/com/example/pitching/user/dto/UserResponse.java
  src/main/resources/application.yml
Labels: documentation, refactor, feat

#43 Aim 178 add user data
  src/main/java/com/example/pitching/auth/domain/User.java
  src/main/java/com/example/pitching/auth/dto/UserInfo.java
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/pitching/auth/repository/UserRepository.java
  src/main/java/com/example/pitching/auth/service/AuthService.java
  src/main/resources/schema.sql
  src/test/java/com/example/pitching/auth/controller/AuthControllerTest.java
  src/test/java/com/example/pitching/user/repository/UserServerMembershipRepositoryTest.java
  src/test/resources/chema-test.sql
Labels: refactor, feat, fix

#45 Aim 185 add user id to the jwt payload
  src/main/java/com/example/pitching/auth/jwt/JwtTokenProvider.java
  src/main/java/com/example/pitching/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/pitching/auth/service/AuthService.java
  src/test/java/com/example/pitching/auth/jwt/JwtAuthenticationTest.java
  src/test/java/com/example/pitching/auth/jwt/JwtTokenProviderTest.java
  src/test/java/com/example/pitching/auth/oauth2/handler/OAuth2HandlerTest.java
  src/test/java/com/example/pitching/auth/service/AuthServiceTest.java
Labels: refactor, feat

#46 Aim 176 implement chat
  build.gradle
  src/main/java/com/example/pitching/auth/config/WebfluxSecurityConfig.java
  src/main/java/com/example/pitching/chat/config/DynamoDBConfig.java
  src/main/java/com/example/pitching/chat/config/WebSocketConfig.java
  src/main/java/com/example/pitching/chat/controller/ChatController.java
  src/main/java/com/example/pitching/chat/domain/ChatMessage.java
  src/main/java/com/example/pitching/chat/dto/ChatMessageDTO.java
  src/main/java/com/example/pitching/chat/dto/UserUpdateMessage.java
  src/main/java/com/example/pitching/chat/handler/ChatWebSocketHandler.java
  src/main/java/com/example/pitching/chat/handler/WebSocketCommand.java
  src/main/java/com/example/pitching/chat/repository/ChatRepository.java
  src/main/java/com/example/pitching/chat/service/ChatService.java
  src/main/java/com/example/pitching/user/controller/ChannelController.java
  src/main/java/com/example/pitching/user/dto/InviteMemberRequest.java
  src/main/java/com/example/pitching/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/example/pitching/chat/controller/ChatControllerTest.java
  src/test/java/com/example/pitching/chat/service/ChatServiceTest.java
Labels: refactor, feat

#50 Aim 207 hot fix 1
  Dockerfile
  src/main/java/com/example/pitching/call/config/RedisConfig.java
  src/main/java/com/example/pitching/call/handler/CallWebSocketHandler.java
Labels: fix

#52 Aim 209 hotfix 2
  Dockerfile
  src/test/java/com/example/pitching/chat/controller/ChatControllerTest.java
  src/test/java/com/example/pitching/chat/service/ChatServiceTest.java
Labels: fix

#53 Aim 204 replace image storage with s3
  build.gradle
  src/main/java/com/example/pitching/chat/config/WebSocketConfig.java
  src/main/java/com/example/pitching/user/config/S3Config.java
  src/main/java/com/example/pitching/user/service/S3FileStorageService.java
  src/main/java/com/example/pitching/user/service/ServerService.java
  src/main/java/com/example/pitching/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/example/pitching/chat/config/DynamoDBConfigTest.java
  src/test/java/com/example/pitching/chat/config/WebSocketConfigTest.java
  src/test/java/com/example/pitching/chat/controller/ChatControllerTest.java
  src/test/java/com/example/pitching/chat/handler/ChatWebSocketHandlerTest.java
  src/test/java/com/example/pitching/chat/service/ChatServiceTest.java
  src/test/java/com/example/pitching/user/controller/ChannelControllerTest.java
  src/test/java/com/example/pitching/user/service/ServerServiceTest.java
  src/test/java/com/example/pitching/user/service/UserServiceTest.java
  src/test/resources/application-test.yml
Labels: refactor

#54 Aim 201 apply rabbit mq redis
  build.gradle
  src/main/java/com/example/pitching/chat/config/RabbitMQConfig.java
  src/main/java/com/example/pitching/chat/handler/ChatWebSocketHandler.java
  src/main/java/com/example/pitching/chat/repository/ChatRedisRepository.java
  src/main/java/com/example/pitching/chat/service/ChatMessageProcessor.java
  src/main/java/com/example/pitching/chat/service/ChatService.java
  src/main/resources/application.yml
  src/test/java/com/example/pitching/chat/handler/ChatWebSocketHandlerTest.java
  src/test/java/com/example/pitching/chat/service/ChatServiceTest.java
Labels: refactor, feat, fix

#56 Aim 214 apply a limit of 100 users per server
  src/main/java/com/example/pitching/user/service/ServerMemberCounter.java
  src/main/java/com/example/pitching/user/service/ServerService.java
  src/test/java/com/example/pitching/user/service/ServerServiceTest.java
Labels: feat, fix

#58 Aim 218 fix bug
  src/main/java/com/example/pitching/chat/repository/ChatRedisRepository.java
  src/main/java/com/example/pitching/chat/repository/ChatRepository.java
  src/main/java/com/example/pitching/user/service/UserService.java
  src/main/resources/application.yml
Labels: fix
